openapi: 3.0.0
servers:
  - url: https://testsoat.interseguro.com.pe/soat/general/
info:
  version: "1.0.0-oas3"
  title: Seguro Vehicular
  description: >
    ¡Bienvenido a la API de seguro vehicular! 

    Esta documentación proporciona instrucciones para acceder a la API y debería
    ayudarlo a familiarizarse con los recursos disponibles.
     ### Cómo empezar
     ----------------------------------------------------------------
     El acceso a la API requiere un token de acceso que se usará en solicitudes posteriores como consultas, registros y actualizaciones
     ### Solicitud de token de acceso
     ----------------------------------------------------------------
     Para obtener su token de acceso deberá llamar al siguiente método POST
       `testsoat.interseguro.com.pe/soat/oauth/token`
     Ingresando como parámetros su información (como grand_type, el ID y el secreto de cliente)
     Si se aprueba esta petición, se le proporcionará un token de acceso
tags:
  - name: Autenticación
  - name: Autos
  - name: Clientes
  - name: Otras Consultas
  - name: Ubigeo
paths:
  /oauth/token:
    post:
      tags:
        - Autenticación
      summary: Obtener un token de autenticación
      parameters:
        - name: grant_type
          in: query
          description: tipo de acceso
          required: true
          schema:
            type: string
        - name: client_id
          in: header
          description: Identificador
          required: true
          schema:
            type: string
        - name: client_secret
          in: query
          description: ' Clave'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: success
          content:
            'application/json':
              schema:
                type: string
                example:
                  access_token: string
                  token_type: string
                  expires_in: 0
        '401':
          description: No Autorizado
  /auto:
    post:
      tags:
        - Autos
      summary: Crear un nuevo registro de auto
      parameters:
        - $ref: '#/components/parameters/Authorization'
      requestBody:
        required: true
        content:
          application/json:
            schema:
               $ref: '#/components/schemas/Auto'
      responses:
        '200':
          description: Ok
    put:
      tags:
        - Autos
      summary: Actualiza la información de un auto
      parameters:
        - $ref: '#/components/parameters/Authorization'
      requestBody:
        required: true
        content:
          application/json:
            schema:
               $ref: '#/components/schemas/Auto'
      responses:
        '200':
          description: Ok
  /auto/placa:
    get:
      tags:
        - Autos
      parameters:
        - $ref: '#/components/parameters/placa'
      summary: Buscar datos de auto
   
      responses:
        '200':
          description: Ok
          content:
            'application/json':
              schema:
                type: object
                example:
                  success: true 
                  mensaje: 'null'
                  extra: 'null'
                  item:
                    placa: C5R38D
                    clase: xxx
                    uso: Particular
                    marca: Toyota
                    modelo: Corolla
                    idClase: 001
                    idMarca: 002
                    idModelo: 003
                    año_fabricacion: '2012'
                    num_asientos: '4'
                    num_serie: MD3FCE0CA421928
                  items: 'null'
        '404':
          description: NOT FOUND
      
  /cliente:
    post:
      tags:
        - Clientes
      summary: Crear un nuevo registro de cliente.
      parameters:
        - $ref: '#/components/parameters/Authorization'
      requestBody:
        required: true
        content:
          application/json:
            schema:
               $ref: '#/components/schemas/Cliente'
      responses:
        '200':
          description: Ok
    put:
      tags:
        - Clientes
      summary: Actualiza la información de un cliente
      parameters:
        - $ref: '#/components/parameters/Authorization'
      requestBody:
        required: true
        content:
          application/json:
            schema:
               $ref: '#/components/schemas/Cliente'
      responses:
        '200':
          description: Ok
        '404':
          description: el recurso de destino no existe
  /cliente/documento:
    get:
      tags:
        - Clientes
      summary: Consultar cliente
      parameters:
        - $ref: '#/components/parameters/documento'
      responses:
        '200':
          description: Ok
          content:
            'application/json':
              schema:
                type: object
                example:
                  success: true 
                  mensaje: 'null'
                  extra: 'null'
                  item:
                    documento: 02658145
                    tipo de documento: DNI
                    nombre: Jose
                    ape_paterno: Flores
                    ape_materno: Seminario
                    direccion: xxx
                    email: jflores@gmail.com
                    fecha_nac : dd/mm/yy
                    iddepartamento: 15
                    departamento: Lima
                    idprovincia: 12
                    drovincia: Lima
                    iddistrito: 8
                    distrito: La Molina
                    movil: '985624159'
                  items: 'null'
        '404':
          description: NOT FOUND
  /marcas:
    post:
      summary: consulta marcas
      tags:
        - Otras Consultas
      responses:
        '200':
          description: Ok
          content:
            'application/json':
              schema:
                type: string
                example:
                  id: '44'
                  descripcion: '5'
                  Ford: '11'
                  Ferrari: '9'
  /modelos:
    post:
      tags:
        - Otras Consultas
      summary: Consulta modelos
      parameters:
        - $ref: '#/components/parameters/marca'
      responses:
        '200':
          description: Ok
          content:
            'application/json':
              schema:
                type: string
                example:
                  AURIS: '1270295'
                  Cynos: '1270156'
                  FORTUNER: '1276694'
                  YARIS: '1271224'
  /clases:
    post:
      tags:
        - Otras Consultas
      summary: Consulta clases
      responses:
        '200':
          description: Ok
          content:
            'application/json':
              schema:
                type: string
                example:
                  AUTOMOVIL: '1'
                  CAMION: '5'
                  CAMIONETA PANEL: '7'
                  CAMIONETA PICK UP: '4'
  /usos:
    post:
      tags:
        - Otras Consultas
      summary: Consulta usos
      responses:
        '200':
          description: Ok
          content:
            'application/json':
              schema:
                type: string
                example:
                  CARGA / TRANSPORTE: '9'
                  PARTICULAR: '4'
                  TAXI: '8'
  /departamentos:
    post:
      summary: consulta Departamentos
      tags:
        - Ubigeo
      responses:
        '200':
          description: Ok
          content:
            'application/json':
              schema:
                  type: object
                  example:
                    success: true 
                    mensaje: 'null'
                    extra: 'null'
                    item: 'null'
                    items:
                    - id: 1
                      nombre: LIMA
                    - id: 2
                      nombre: PIURA
                    - id: 3
                      nombre: AREQUIPA
                    - id: 4
                      nombre: TRUJILLO
  /provincias:
    post:
      summary: consulta Provincias
      tags:
        - Ubigeo
      responses:
        '200':
          description: Ok
          content:
            'application/json':
              schema:
                type: object
                example:
                  success: true 
                  mensaje: 'null'
                  extra: 'null'
                  item: 'null'
                  items:
                  - id: 1
                    nombre: LIMA
                  - id: 2
                    nombre: CALLAO
                  - id: 3
                    nombre: AREQUIPA
                  - id: 4
                    nombre: CAJAMARCA
  /distritos:
    post:
      summary: consulta Distritos
      tags:
        - Ubigeo
      responses:
        '200':
          description: Ok
          content:
            'application/json':
              schema:
                type: object
                example:
                  success: true 
                  mensaje: 'null'
                  extra: 'null'
                  item: 'null'
                  items:
                  - id: 1
                    nombre: SAN JUAN DE MIRAFLORES
                  - id: 2
                    nombre: SAN ISIDRO
                  - id: 3
                    nombre: SAN LUIS 
                  - id: 4
                    nombre: SAN MARTIN DE PORRES
components:
  schemas:
    Auto:
      type: object
      properties:
        placa:
          type: string  
        anio_fabricacion: 
          type: number
        idclase: 
          type: number
        iduso: 
          type: number
        idmarca: 
          type: number
        idmodelo: 
          type: number
        num_asientos: 
          type: number
        num_serie: 
          type: number
    Cliente:
      type: object
      properties:
        nombre:
          type: string  
        ape_paterno: 
          type: string
        ap_materno: 
          type: string
        documento: 
          type: number
        email: 
          type: string
        movil: 
          type: number
        departamento: 
          type: string
        provincia: 
          type: string
        distrito:
          type: string
  parameters:
    Authorization:
      name: Authorization
      in: header
      description: Llave de autorización
      required: true
      schema:
        type: string
    placa:
      name: placa
      in: query
      description: placa
      required: true
      schema:
        type: string
    clase:
      name: idclase
      in: query
      description: clase
      required: true
      schema:
        type: number
    uso:
      name: iduso
      in: query
      description: Uso
      required: true
      schema:
        type: number
    marca:
      name: idmarca
      in: query
      description: marca
      required: true
      schema:
        type: number
    modelo:
      name: idmodelo
      in: query
      description: modelo
      required: true
      schema:
        type: number
    fabricacion:
      name: anio_fabricacion
      in: query
      description: Año de fabricación
      required: true
      schema:
        type: string
    num_asientos:
      name: num_asientos
      in: query
      description: Número de asientos
      required: true
      schema:
        type: string
    num_serie:
      name: num_serie
      in: query
      description: Número de serie
      required: true
      schema:
        type: string
    documento:
      name: documento
      in: query
      description: Número de Documento
      required: true
      schema:
        type: number
    nombre:
      name: nombre
      in: query
      description: nombre del cliente
      required: true
      schema:
        type: string
    ape_paterno:
      name: ape_paterno
      in: query
      description: Apellido Paterno
      required: true
      schema:
        type: string
    ape_materno:
      name: ape_materno
      in: query
      description: Apellido Materno
      required: true
      schema:
        type: string
    email:
      name: email
      in: query
      description: Correo electrónico
      required: true
      schema:
        type: string
    movil:
      name: movil
      in: query
      description: Número de celular
      required: true
      schema:
        type: string
    departamento:
      name: departamento
      in: query
      description: Departamento
      required: true
      schema:
        type: string
    provincia:
      name: provincia
      in: query
      description: Provincia
      required: true
      schema:
        type: string
    distrito:
      name: distrito
      in: query
      description: Distrito
      required: true
      schema:
        type: string