{
  "openapi" : "3.0.0",
  "servers" : [ {
    "url" : "https://testsoat.interseguro.com.pe/api-vehicular/v1"
  } ],
  "info" : {
    "version" : "1.0.0-oas3",
    "title" : "Seguro Vehicular",
    "description" : "¡Bienvenido a la API de seguro vehicular! \nEsta documentación proporciona instrucciones para acceder a la API y debería ayudarlo a familiarizarse con los recursos disponibles.\n ### Cómo empezar\n ----------------------------------------------------------------\n El acceso a la API requiere un token de acceso que se usará en solicitudes posteriores como consultas, registros y actualizaciones\n ### Solicitud de token de acceso\n ----------------------------------------------------------------\n Para obtener su token de acceso deberá llamar al siguiente método POST\n   `testsoat.interseguro.com.pe/api-vehicular/v1/oauth/access_token`\n Ingresando como parámetros su información (como grand_type, el ID y el secreto de cliente)\n Si se aprueba esta petición, se le proporcionará un token de acceso\n"
  },
  "tags" : [ {
    "name" : "Autenticación"
  }, {
    "name" : "Autos"
  }, {
    "name" : "Clientes"
  }, {
    "name" : "Otras Consultas"
  }, {
    "name" : "Ubigeo"
  } ],
  "paths" : {
    "/oauth/access_token" : {
      "post" : {
        "tags" : [ "Autenticación" ],
        "summary" : "Obtener un token de autenticación",
        "requestBody" : {
          "required" : true,
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/acces_token"
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "success",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "string",
                  "example" : {
                    "access_token" : "string",
                    "token_type" : "string",
                    "expires_in" : 0
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auto" : {
      "post" : {
        "tags" : [ "Autos" ],
        "summary" : "Crear un nuevo registro de auto",
        "parameters" : [ {
          "$ref" : "#/components/parameters/Authorization"
        } ],
        "requestBody" : {
          "required" : true,
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/Auto"
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "Ok",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "example" : {
                    "success" : true,
                    "mensaje" : "null",
                    "extra" : "null",
                    "item" : "null",
                    "items" : "null"
                  }
                }
              }
            }
          }
        }
      },
      "put" : {
        "tags" : [ "Autos" ],
        "summary" : "Actualiza la información de un auto",
        "parameters" : [ {
          "$ref" : "#/components/parameters/Authorization"
        } ],
        "requestBody" : {
          "required" : true,
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/Auto"
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "Ok",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "example" : {
                    "success" : true,
                    "mensaje" : "null",
                    "extra" : "null",
                    "item" : "null",
                    "items" : "null"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auto/{placa}" : {
      "get" : {
        "tags" : [ "Autos" ],
        "parameters" : [ {
          "$ref" : "#/components/parameters/Authorization"
        }, {
          "$ref" : "#/components/parameters/placa"
        } ],
        "summary" : "Buscar datos de auto",
        "responses" : {
          "200" : {
            "description" : "Ok",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "example" : {
                    "success" : true,
                    "mensaje" : "null",
                    "extra" : "null",
                    "item" : {
                      "placa" : "C5R38D",
                      "clase" : "Automovil",
                      "uso" : "Particular",
                      "marca" : "Toyota",
                      "modelo" : "Corolla",
                      "idclase" : 1,
                      "idmarca" : 2,
                      "idmodelo" : 3,
                      "anio_fabricacion" : 2012,
                      "num_asientos" : 4,
                      "num_serie" : "MD3FCE0CA421928"
                    },
                    "items" : "null"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/cliente" : {
      "post" : {
        "tags" : [ "Clientes" ],
        "summary" : "Crear un nuevo registro de cliente.",
        "parameters" : [ {
          "$ref" : "#/components/parameters/Authorization"
        } ],
        "requestBody" : {
          "required" : true,
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/Cliente"
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "Ok",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "example" : {
                    "success" : true,
                    "mensaje" : "null",
                    "extra" : 16345709,
                    "item" : "null",
                    "items" : "null"
                  }
                }
              }
            }
          }
        }
      },
      "put" : {
        "tags" : [ "Clientes" ],
        "summary" : "Actualiza la información de un cliente",
        "parameters" : [ {
          "$ref" : "#/components/parameters/Authorization"
        } ],
        "requestBody" : {
          "required" : true,
          "content" : {
            "application/json" : {
              "schema" : {
                "type" : "object",
                "required" : [ "nombre", "ape_paterno", "ape_materno", "documento", "email", "celular", "iddepartamento", "idprovincia", "iddistrito" ],
                "properties" : {
                  "idcliente" : {
                    "type" : "string"
                  },
                  "documento" : {
                    "type" : "string"
                  },
                  "nombre" : {
                    "type" : "string"
                  },
                  "ape_paterno" : {
                    "type" : "string"
                  },
                  "ape_materno" : {
                    "type" : "string"
                  },
                  "fecha_nac" : {
                    "type" : "string"
                  },
                  "email" : {
                    "type" : "string"
                  },
                  "celular" : {
                    "type" : "string"
                  },
                  "iddepartamento" : {
                    "type" : "number"
                  },
                  "idprovincia" : {
                    "type" : "number"
                  },
                  "iddistrito" : {
                    "type" : "number"
                  }
                }
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "Ok",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "example" : {
                    "success" : true,
                    "mensaje" : "null",
                    "extra" : "null",
                    "item" : "null",
                    "items" : "null"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/cliente/{documento}" : {
      "get" : {
        "tags" : [ "Clientes" ],
        "summary" : "Consultar cliente",
        "parameters" : [ {
          "$ref" : "#/components/parameters/Authorization"
        }, {
          "$ref" : "#/components/parameters/documento"
        } ],
        "responses" : {
          "200" : {
            "description" : "Ok",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "example" : {
                    "success" : true,
                    "mensaje" : "null",
                    "extra" : "null",
                    "item" : {
                      "idcliente" : 16345709,
                      "documento" : 2658145.0,
                      "tipo_documento" : "DNI",
                      "nombre" : "Juan Manuel",
                      "ape_paterno" : "Soto",
                      "ape_materno" : "Gutierrez",
                      "direccion" : "Calle Falsa 123",
                      "email" : "vehicular@yopmail.com",
                      "celular" : "987456123",
                      "fecha_nac" : "dd/mm/yyyy",
                      "iddepartamento" : 15,
                      "departamento" : "Lima",
                      "idprovincia" : 134,
                      "provincia" : "Lima",
                      "iddistrito" : 1340,
                      "distrito" : "Cercado de Lima"
                    },
                    "items" : "null"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/marcas" : {
      "parameters" : [ {
        "$ref" : "#/components/parameters/Authorization"
      } ],
      "post" : {
        "summary" : "consulta marcas",
        "tags" : [ "Otras Consultas" ],
        "responses" : {
          "200" : {
            "description" : "Ok",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "string",
                  "example" : {
                    "success" : true,
                    "mensaje" : "null",
                    "extra" : "null",
                    "item" : "null",
                    "items" : [ {
                      "id" : 44,
                      "nombre" : "Ford"
                    }, {
                      "id" : 20,
                      "nombre" : "Ferrari"
                    }, {
                      "id" : 10,
                      "nombre" : "FIAT"
                    }, {
                      "id" : 11,
                      "nombre" : "FOTON"
                    } ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/modelos" : {
      "post" : {
        "tags" : [ "Otras Consultas" ],
        "summary" : "Consulta modelos",
        "parameters" : [ {
          "$ref" : "#/components/parameters/Authorization"
        } ],
        "requestBody" : {
          "required" : true,
          "content" : {
            "application/json" : {
              "schema" : {
                "type" : "object",
                "required" : [ "idmarca" ],
                "properties" : {
                  "idmarca" : {
                    "type" : "number"
                  }
                }
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "Ok",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "string",
                  "example" : {
                    "success" : true,
                    "mensaje" : "null",
                    "extra" : "null",
                    "item" : "null",
                    "items" : [ {
                      "id" : 1270295,
                      "nombre" : "AURIS"
                    }, {
                      "id" : 1270156,
                      "nombre" : "Cynos"
                    }, {
                      "id" : 1276694,
                      "nombre" : "FORTUNER"
                    }, {
                      "id" : 1271224,
                      "nombre" : "YARIS"
                    } ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/clases" : {
      "post" : {
        "tags" : [ "Otras Consultas" ],
        "parameters" : [ {
          "$ref" : "#/components/parameters/Authorization"
        } ],
        "summary" : "Consulta clases",
        "responses" : {
          "200" : {
            "description" : "Ok",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "string",
                  "example" : {
                    "success" : true,
                    "mensaje" : "null",
                    "extra" : "null",
                    "item" : "null",
                    "items" : [ {
                      "id" : 1,
                      "nombre" : "AUTOMOVIL"
                    }, {
                      "id" : 5,
                      "nombre" : "CAMION"
                    }, {
                      "id" : 7,
                      "nombre" : "CAMIONETA PICK UP"
                    }, {
                      "id" : 4,
                      "nombre" : "CAMIONETA PANEL"
                    } ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/usos" : {
      "post" : {
        "tags" : [ "Otras Consultas" ],
        "summary" : "Consulta usos",
        "parameters" : [ {
          "$ref" : "#/components/parameters/Authorization"
        } ],
        "responses" : {
          "200" : {
            "description" : "Ok",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "string",
                  "example" : {
                    "success" : true,
                    "mensaje" : "null",
                    "extra" : "null",
                    "item" : "null",
                    "items" : [ {
                      "id" : 4,
                      "nombre" : "CARGA / TRANSPORTE"
                    }, {
                      "id" : 8,
                      "nombre" : "PARTICULAR"
                    }, {
                      "id" : 9,
                      "nombre" : "TAXI"
                    } ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/departamentos" : {
      "post" : {
        "summary" : "consulta Departamentos",
        "parameters" : [ {
          "$ref" : "#/components/parameters/Authorization"
        } ],
        "tags" : [ "Ubigeo" ],
        "responses" : {
          "200" : {
            "description" : "Ok",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "example" : {
                    "success" : true,
                    "mensaje" : "null",
                    "extra" : "null",
                    "item" : "null",
                    "items" : [ {
                      "id" : 1,
                      "nombre" : "LIMA"
                    }, {
                      "id" : 2,
                      "nombre" : "PIURA"
                    }, {
                      "id" : 3,
                      "nombre" : "AREQUIPA"
                    }, {
                      "id" : 4,
                      "nombre" : "TRUJILLO"
                    } ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/provincias" : {
      "post" : {
        "summary" : "consulta Provincias",
        "tags" : [ "Ubigeo" ],
        "parameters" : [ {
          "$ref" : "#/components/parameters/Authorization"
        } ],
        "requestBody" : {
          "required" : true,
          "content" : {
            "application/json" : {
              "schema" : {
                "type" : "object",
                "required" : [ "iddepartamento" ],
                "properties" : {
                  "iddepartamento" : {
                    "type" : "number"
                  }
                }
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "Ok",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "example" : {
                    "success" : true,
                    "mensaje" : "null",
                    "extra" : "null",
                    "item" : "null",
                    "items" : [ {
                      "id" : 1,
                      "nombre" : "LIMA"
                    }, {
                      "id" : 2,
                      "nombre" : "CALLAO"
                    }, {
                      "id" : 3,
                      "nombre" : "AREQUIPA"
                    }, {
                      "id" : 4,
                      "nombre" : "CAJAMARCA"
                    } ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/distritos" : {
      "post" : {
        "summary" : "consulta Distritos",
        "tags" : [ "Ubigeo" ],
        "parameters" : [ {
          "$ref" : "#/components/parameters/Authorization"
        } ],
        "requestBody" : {
          "required" : true,
          "content" : {
            "application/json" : {
              "schema" : {
                "type" : "object",
                "required" : [ "idprovincia", "iddistrito" ],
                "properties" : {
                  "idprovincia" : {
                    "type" : "number"
                  },
                  "iddistrito" : {
                    "type" : "number"
                  }
                }
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "Ok",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "example" : {
                    "success" : true,
                    "mensaje" : "null",
                    "extra" : "null",
                    "item" : "null",
                    "items" : [ {
                      "id" : 1,
                      "nombre" : "SAN JUAN DE MIRAFLORES"
                    }, {
                      "id" : 2,
                      "nombre" : "SAN ISIDRO"
                    }, {
                      "id" : 3,
                      "nombre" : "SAN LUIS"
                    }, {
                      "id" : 4,
                      "nombre" : "SAN MARTIN DE PORRES"
                    } ]
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "acces_token" : {
        "type" : "object",
        "properties" : {
          "grant_type" : {
            "type" : "string"
          },
          "client_id" : {
            "type" : "string"
          },
          "client_secret" : {
            "type" : "string"
          }
        }
      },
      "Auto" : {
        "type" : "object",
        "required" : [ "placa", "anio_fabricacion", "idclase", "iduso", "idmarca", "idmodelo", "num_asientos", "num_serie" ],
        "properties" : {
          "placa" : {
            "type" : "string"
          },
          "anio_fabricacion" : {
            "type" : "number"
          },
          "idclase" : {
            "type" : "number"
          },
          "iduso" : {
            "type" : "number"
          },
          "idmarca" : {
            "type" : "number"
          },
          "idmodelo" : {
            "type" : "number"
          },
          "num_asientos" : {
            "type" : "number"
          },
          "num_serie" : {
            "type" : "string"
          }
        }
      },
      "Cliente" : {
        "type" : "object",
        "required" : [ "nombre", "ape_paterno", "ape_materno", "documento", "email", "celular", "iddepartamento", "idprovincia", "iddistrito" ],
        "properties" : {
          "documento" : {
            "type" : "string"
          },
          "nombre" : {
            "type" : "string"
          },
          "ape_paterno" : {
            "type" : "string"
          },
          "ape_materno" : {
            "type" : "string"
          },
          "fecha_nac" : {
            "type" : "string"
          },
          "email" : {
            "type" : "string"
          },
          "celular" : {
            "type" : "string"
          },
          "iddepartamento" : {
            "type" : "number"
          },
          "idprovincia" : {
            "type" : "number"
          },
          "iddistrito" : {
            "type" : "number"
          }
        }
      }
    },
    "parameters" : {
      "Authorization" : {
        "name" : "Authorization",
        "in" : "header",
        "description" : "Llave de autorización (Ej. Bearer token_recibido)",
        "required" : true,
        "schema" : {
          "type" : "string"
        }
      },
      "placa" : {
        "name" : "placa",
        "in" : "path",
        "description" : "placa",
        "required" : true,
        "schema" : {
          "type" : "string"
        }
      },
      "clase" : {
        "name" : "idclase",
        "in" : "query",
        "description" : "clase",
        "required" : true,
        "schema" : {
          "type" : "number"
        }
      },
      "uso" : {
        "name" : "iduso",
        "in" : "query",
        "description" : "Uso",
        "required" : true,
        "schema" : {
          "type" : "number"
        }
      },
      "marca" : {
        "name" : "idmarca",
        "in" : "query",
        "description" : "marca",
        "required" : true,
        "schema" : {
          "type" : "number"
        }
      },
      "modelo" : {
        "name" : "idmodelo",
        "in" : "query",
        "description" : "modelo",
        "required" : true,
        "schema" : {
          "type" : "number"
        }
      },
      "fabricacion" : {
        "name" : "anio_fabricacion",
        "in" : "query",
        "description" : "Año de fabricación",
        "required" : true,
        "schema" : {
          "type" : "string"
        }
      },
      "num_asientos" : {
        "name" : "num_asientos",
        "in" : "query",
        "description" : "Número de asientos",
        "required" : true,
        "schema" : {
          "type" : "string"
        }
      },
      "num_serie" : {
        "name" : "num_serie",
        "in" : "query",
        "description" : "Número de serie",
        "required" : true,
        "schema" : {
          "type" : "string"
        }
      },
      "documento" : {
        "name" : "documento",
        "in" : "path",
        "description" : "Número de Documento",
        "required" : true,
        "schema" : {
          "type" : "string"
        }
      },
      "nombre" : {
        "name" : "nombre",
        "in" : "query",
        "description" : "nombre del cliente",
        "required" : true,
        "schema" : {
          "type" : "string"
        }
      },
      "ape_paterno" : {
        "name" : "ape_paterno",
        "in" : "query",
        "description" : "Apellido Paterno",
        "required" : true,
        "schema" : {
          "type" : "string"
        }
      },
      "ape_materno" : {
        "name" : "ape_materno",
        "in" : "query",
        "description" : "Apellido Materno",
        "required" : true,
        "schema" : {
          "type" : "string"
        }
      },
      "email" : {
        "name" : "email",
        "in" : "query",
        "description" : "Correo electrónico",
        "required" : true,
        "schema" : {
          "type" : "string"
        }
      },
      "celular" : {
        "name" : "celular",
        "in" : "query",
        "description" : "Número de celular",
        "required" : true,
        "schema" : {
          "type" : "string"
        }
      },
      "departamento" : {
        "name" : "departamento",
        "in" : "query",
        "description" : "Departamento",
        "required" : true,
        "schema" : {
          "type" : "string"
        }
      },
      "provincia" : {
        "name" : "provincia",
        "in" : "query",
        "description" : "Provincia",
        "required" : true,
        "schema" : {
          "type" : "string"
        }
      },
      "distrito" : {
        "name" : "distrito",
        "in" : "query",
        "description" : "Distrito",
        "required" : true,
        "schema" : {
          "type" : "string"
        }
      }
    }
  }
}